version: '3.8'

services:
  app:
    image: 'ghapp:latest'
    container_name: ghapp
    depends_on:
      - db
    environment:
      - POSTGRES_USER=neqrofukk
      - POSTGRES_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ghappdb
      - SPRING_DATASOURCE_USERNAME=neqrofukk
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=neqrofukk
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ghappdb
    ports:
      - "5432:5432"