spring.application.name=githubrepo
github.api.url=https://api.github.com/repos
springdoc.api-docs.path=/api-docs

#spring.datasource.url=jdbc:h2:mem:demodb;DB_CLOSE_DELAY=-1;
spring.datasource.url=jdbc:postgresql://localhost:5432/ghappdb
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neqrofukk
spring.datasource.password=123456
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.trace=false
#spring.h2.console.settings.web-allow-others=false

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.neqrofukk.githubrepo.demo=DEBUG
logging.level.liquibase=DEBUG

spring.mvc.problemdetails.enabled=true

spring.cloud.openfeign.client.config.default.connect-timeout=3000
spring.cloud.openfeign.client.config.default.read-timeout=5000
spring.cloud.openfeign.circuitbreaker.enabled=true